### ISSUE TITLE
External codes not linked to siteID, what's the harm?

### ISSUE THREAD

**Issue by vccs** [mgazdzik/plugin-ShortcodeTracker#41] opened 2021-02-16 02:49 UTC
Hi thanks very much for this great plugin!

So creating and viewing External codes seems to be restricted to superadmin as they aren't bound to any siteid by nature, rather attributed to a site for tracking in the settings. As a result, users without superadmin rights can't use Externals. Is there any reason we can't attribute a siteID to externals so they can be created by site admins and track the data in that sites external reporting tab? It seems we'd just need to add the entry to the DB.

I'm hoping to better understand the thought process and what I might be missing.

Thanks.

**Comment by mgazdzik** [comment] 2021-02-16 15:58
Hello Matt! 

I'm super happy that you find my humble plugin useful, that's best thing to read :) 

As for external codes, please find below my thinking process:
- in order to track external redirects we need to point a site to contain all those actions
- without this special site it's essentially pointless to me to run such shortener if you can't see what's happening
- so if we have this site created and assigned in settings there is matter of creating new codes
- codes are stored in single table, with not much of optimization so far, so I'd recognize that you should be at least admin in given Matomo instance to create new entities, especially ones which can come in big numbers
- therefore the least required access to create shortcode (it's actually for any shortcode) is admin of any single page
- so if you want to grant user explicitly permissions to create external shortcodes - just grant him admin privilege to site holding external redirects
- external redirect site should hold relatively safe data, without risk of giving away too much info about other configured sites
- that way we also eliminate risk that somebody with "view only access" will create too much entries in database 

Therefore TL;DR - if you're tracking externals with separate site - just give your target user admin to that site, should work like a charm :)

I realize that this could be done in different way, but also so far there's not much discussion about it so if that works for you I'd rather close the ticket for now :)

Please let me know does my thinking process make sense? 

Best,
Michael

**Comment by vccs** [comment] 2021-02-16 17:00
Hey Michael, thanks for the in-depth response! One clarification please;

I definitely want to track external shortcode usage but I'm wondering; why don't we assign the SiteID to the code from where it was generated? Why do we need to assign all external code reporting to just 1 single site ID? What if we change the siteID value from 0 to the siteID that generated it, in the DB?

Basically if admin user of site xyz.com generates an external shortcode, I want his shortcode to be tracked in his site like Internal shortcodes are. Is there any issue with assigning the SiteID on generation so it doesn't default to 0?

---------------
(resolved my comment after about the error. The admin user has to be admin of the site ID where externals collect data).

**Comment by mgazdzik** [comment] 2021-02-17 07:27
The reason for that choice is that in my initial thought external shortcodes are not something we should put into other websites in Matomo for sake of data integrity. 
My concept was that since Matomo defines website as set of domains and collects actions only for those domains - I don't want to collect actions for non-tracked domains. Hence there's possibility to set up separate website to collect all those external redirects. 
Although if you want to track external redirects for known set of domains, I do believe that you can just add them to the desired website in matomo and plugin will catch those "externals" into this website.
I'm not sure if changing siteId field for shortcode will force tracking redirect into desired site, I'd suggest simply checking it out :) 

Please let me know if above "hack" is of any help to your use case?

If this doesn't help then I'm afraid it would take some reworking of plugin itself to allow such action as, to be honest, I didn't think of such use :) 

Cheers!

**Comment by vccs** [comment] 2021-02-17 16:20
Great feedback. I actually went ahead and tried it in the meantime. The visitors log reflects the visitor data as well as the external reporting of the code. 

Appreciate your feedback. Are you available off board for some potential customizing? I can email you if so.

Thanks again.

**Comment by mgazdzik** [comment] 2021-02-17 17:56
Sure, please feel free to drop me a line on my email, maybe I can help somehow :)

Also if that's all for the issue discussion, I'm closing it for now. should anything else pop out anytime feel free to reopen.

**Comment by Bruno-adi** [comment] 2021-03-16 16:46
Hello,

thank you for this detailed information.

I'm sorry to reopen this ticket but I think I have an identical problem, without having solved it.

The plugin works for my super admin, but not for site admins.
I keep getting the message "your session has expired due to inactivity, please log in again".

If the user is not "Admin" the shortcode creation menu does not appear.

The plugin is configured with a "Site id for tracking external shortcode redirects" - my test users are Admins of this site.

it's so frustrating :-), everything works perfectly in super-admin.

**Comment by mgazdzik** [comment] 2021-03-16 17:59
Hello, 

I'm very sorry to hear that, I hope I can help you somehow solve that.
As far as I know the plugin doesn't interfere with user session, so it's super weird that this is happening.
In order to try debugging this issue can I ask you to send me a little bit more detailed information about what actions are you actually taking when the problem occurs, maybe some screenshots too? Can be on my email if that's ok with you.
Also I could use info about your Matomo instance version and plugin version.
Hopefully this information will allow me to reproduce the problem on my end and fix that :) 

Best,
Michael

**Comment by mgazdzik** [comment] 2021-03-18 09:45
Issue was resolved in 2.0.1 version, closing :)

**Closed as completed by mgazdzik** 2021-03-18 09:45 UTC
