### ISSUE TITLE
Matomo shortcode interface cannot dispay any page except "Generate Shortcode"

### ISSUE THREAD

**Issue by Tc-001** [mgazdzik/plugin-ShortcodeTracker#45] opened 2021-05-20 11:11 UTC
# Issue
Shortcode generation/redirects work, but matomo UI fails to load any page except "Generate Shortcode".

Loading will fail with an error banner:
> Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance.

Logs show the following:
```
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#13 {main}
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#12 /home/site/public_html/matomo/index.php(25): require_once('/home/site/publ...')
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#11 /home/site/public_html/matomo/core/dispatch.php(32): Piwik\FrontController->dispatch()
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#10 /home/site/public_html/matomo/core/FrontController.php(167): Piwik\FrontController->doDispatch('ShortcodeTracke...', 'getShortcodeUsa...', Array)
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#9 /home/site/public_html/matomo/core/FrontController.php(615): call_user_func_array(Array, Array)
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#8 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget(Object(Piwik\Plugins\ShortcodeTracker\Reports\GetShortcodeUsageReport))
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#7 /home/site/public_html/matomo/plugins/CoreHome/Controller.php(59): Piwik\Plugin\Report->render()
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#6 /home/site/public_html/matomo/core/Plugin/Report.php(320): Piwik\Plugin\Visualization->render()
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#5 /home/site/public_html/matomo/core/Plugin/Visualization.php(188): Piwik\Plugin\Visualization->loadDataTableFromAPI()
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#4 /home/site/public_html/matomo/core/Plugin/Visualization.php(341): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'getShortcodeUsa...', Array)
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#3 /home/site/public_html/matomo/core/API/Proxy.php(335): Piwik\Context::executeWithQueryParameters(Array, Object(Closure))
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#2 /home/site/public_html/matomo/core/Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}()
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#1 /home/site/public_html/matomo/core/API/Proxy.php(244): call_user_func_array(Array, Array)
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	#0 [internal function]: Piwik\Plugins\ShortcodeTracker\API->getShortcodeUsageReport('1', 'day', 'yesterday', false, false)
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	Stack trace:
ERROR 	Piwik\FrontController 	2021-05-20 10:54:25 UTC 	fae3d 	Uncaught exception: Error: Call to a member function getIdSubDataTable() on boolean in /home/site/public_html/matomo/plugins/ShortcodeTracker/API.php:375
```
# My config
Matomo 4.3.0
PHP 7.2

# Screenshot
(`Shortcode usage report`, `Most shortened pages`, `External shortcode usage` and `Most shortened external pages` will all fail)
![image](https://user-images.githubusercontent.com/55956895/118968335-767a3f00-b974-11eb-9eca-d1062012970f.png)

**Comment by mgazdzik** [comment] 2022-11-22 18:04
@Tc-001 have you tried to force rearchiving the dates that you're trying to view in plugin? Unfortunatelly I cannot reproduce this error on my end so it's difficult to tell what exactly is wrong. 

Closing the issue for now due to it's age, please reopen if the problem still exists.

**Closed as completed** 2022-11-22 18:07 UTC
