### ISSUE TITLE
Cannot generate shortcodes at all

### ISSUE THREAD

**Issue by froger-me** [mgazdzik/plugin-ShortcodeTracker#49] opened 2021-12-16 13:44 UTC
Hi! This plugin looks very promising, but so far I wasn't able to use it.

Fresh install of the WordPress version of the plugin downloaded from [the marketplace](https://plugins.matomo.org/ShortcodeTracker?wp=1)

Attempt to generate code: "Unable to generate shortcode. Please try again providing valid URL."

Digging in the code I reached `Piwik\Plugins\ShortcodeTracker\Component\Generator::checkIfUnique` and checked the return value of `Piwik\Plugins\ShortcodeTracker\Model\Model::selectShortcodeByCode` ; it returns `null`, but `checkIfUnique` is looking for `false` with strict  `===` comparison.

Solution: check for `null`, or (less good practice) use loose comparison operator `==`.

**Comment by mgazdzik** [comment] 2022-11-22 17:59
@froger-me this message you pasted seems to be pointing that you didn't provide a valid URL in the shortcode form, for ex you might be missing protocol or different part. can you please share some more info about how to reproduce that issue?

Closing the issue for now due to it's age, please reopen if the problem still exists.

**Closed as completed** 2022-11-22 18:08 UTC
